package com.miguelalmo.lord_of_rings

import androidx.lifecycle.ViewModel

class MainActivityViewModel: ViewModel() {

    fun loadPersonajes() : List<Personaje> {
        val legolas = Personaje("Legolas","Sindar",itsGood = true,R.mipmap.legolas,"Hijo del rey Thranduil de los elfos del Bosque Negro. Fue a Rivendel para entregar un mensaje de su padre: la criatura Gollum, que había sido apresada y entregada por Gandalf a Thranduil para que lo vigilara, había conseguido escapar. Acabó participando así en el Concilio de Elrond y formando parte de la Compañía del Anillo.")
        val frodo = Personaje("Frodo","Hobbit",itsGood = true,R.mipmap.frodo,"Protagonista de la novela, hijo de Drogo Bolsón y Prímula Brandigamo. Tras la muerte de sus padres, su tío Bilbo le adoptó y le nombró su heredero, hecho que le llevó a poseer el Anillo Único.")
        val gimli = Personaje("Gimli","Enano",itsGood = true,R.mipmap.gimli,"Hijo de Glóin, uno de los enanos que aparecen en El hobbit junto a Thorin. Vivía en Erebor y acompañó a su padre hasta Rivendel para acabar así formando parte de la Compañía del Anillo.")
        val gandalf = Personaje("Gandalf","Istari y Maiar",itsGood = true,R.mipmap.gandalf,"Llamado Olórin en Aman, fue enviado a la Tierra Media en la Tercera Edad del Sol junto con otros cuatro maiar, formando así la Orden de los Istari, cuyo objetivo era combatir a Sauron y proteger de él a los habitantes de la Tierra Media. El elfo Círdan, que fue testigo de su llegada, le entregó uno de los tres anillos élficos, Narya. Hizo numerosos viajes y trató de conocer a todos los pueblos de la Tierra Media, hecho que le condujo a la Comarca y a Bilbo, desencadenando así las historias narradas en El hobbit y El Señor de los Anillos.")
        val aragorn = Personaje("Aragorn","Dúnedai",itsGood = true,R.mipmap.aragorn, "También llamado «Trancos», Estel o Elessar Telcontar, es el hijo de Arathorn II y Gilraen, y el trigésimo noveno heredero del rey Isildur de Arnor por línea directa. Tras la temprana muerte de su padre, se convirtió en el capitán de los dúnedain del Norte y se crio en Rivendel, donde conoció y se enamoró de Arwen, la hija de Elrond. En uno de los numerosos viajes que realizó como montaraz, conoció a Gandalf y se hizo amigo suyo, ayudándole en varias ocasiones.")
        val gollum = Personaje("Gollum","Hobbit(corrupto)",itsGood = false,R.mipmap.gollum,"Anteriormente llamado Sméagol, era un hobbit de la rama de los Fuertes que vivía en los Campos Gladios. Un año, mientras pescaba con su primo Déagol en el Anduin, este encontró el Anillo Único en el fondo del río y Sméagol le asesinó para adueñarse de él. Tras ser desterrado por su pueblo, Sméagol vagó sin rumbo y acabó refugiándose en la Montañas Nubladas, donde el Anillo alargó su vida de forma antinatural y su poder le consumió casi por completo.")
        val sam = Personaje("Sam","Hobbit",itsGood = true,R.mipmap.sam,"Hijo de Hamfast Gamyi y Campanilla Buenchico. Jardinero de Bolsón Cerrado, fiel amigo y protector de su amigo Frodo.")
        val arwen = Personaje("Arwen","Peredhil",itsGood = true,R.mipmap.arwen,"Arwen  (traducido del sindarin como «doncella noble»), también llamada Undómiel («El lucero de la tarde»), era la hija de Elrond y Celebrían. Era hermana de Elladan y Elrohir. Durante siglos vivió entre Rivendel, el refugio y hogar de su padre, y Lothlórien, la tierra natal de su madre. Unos años antes de que finalizara la Tercera Edad del Sol, conoció a Aragorn en los bosques de Rivendel y se enamoraron. Por él renunció a la inmortalidad para convertirse en su esposa y en la reina consorte del Reino Unificado de Gondor y Arnor (Reinaron durante 120 años) tras la Guerra del Anillo.")
        val saruman = Personaje("Saruman","Istari y Ainur",itsGood = false,R.mipmap.saruman,"Fue enviado a la Tierra Media en la Tercera Edad del Sol como líder de los Istari. Sin embargo, se desvió de su misión y trató de encontrar el Anillo Único para él, aliándose con Sauron al usar la palantír de Orthanc.")
        val sauron = Personaje("Sauron","Ainur y Maiar",itsGood = false,R.mipmap.sauron,"Sauron es un ainu, uno de los maiar, contado entre el séquito de Aulë, el herrero. Era el más poderoso de los maiar al servicio de Aulë que fue corrompido por Melkor cuando los ainur aún se encontraban dando forma a Arda. Sauron permanecería en la Tierra Media durante más de 16.000 años, mucho más que todos sus principales enemigos, excepto que quizás Círdan, el carpintero de barcos, y el viejo Tom Bombadil.")
        val boromir = Personaje("Boromir","Hombre(Dúnedai)",itsGood = true,R.mipmap.boromir,"Hijo primogénito del senescal de Gondor, Denethor II, y de Finduilas de Dol Amroth; y el hermano mayor de Faramir. Tuvo un sueño profético sobre el Anillo Único que le llevó hasta Rivendel y a participar así en el Concilio de Elrond.")
        val peregrin = Personaje("Peregrin","Hobbit",itsGood = true,R.mipmap.peregrin,"Apodado 'Pippin', es hijo de Paladin Tuk, Thain de la Comarca, y de Eglantina Ribera. Primo y amigo de Frodo.")
        val reyBrujo = Personaje("Rey Brujo","Nazgûl",itsGood = false,R.mipmap.reybrujo,"Conocido como 'Señor de los Nazgúl' es un espectro, el jefe supremo de los Nazgûl. En vida, pudo haber sido un príncipe de Oesternesse. De los nueve anillos que Sauron forjó para engañar a los hombres, entregó tres a otros tantos señores de los númenóreanos, los más poderosos de entre los hombres, en la Segunda Edad del Sol. Tanto esos tres como los otros seis sucumbieron a su poder y con el tiempo, pasaron a servirle como espectros, ni vivos, ni muertos.")
        val meriadoc = Personaje("Meriadoc","Hobbit",itsGood = true,R.mipmap.meriadoc,"Apodado 'Merry', es hijo de Saradoc Brandigamo, Señor de los Gamos, y de Esmeralda Tuk. Primo y amigo de Frodo.")
        val grima = Personaje("Gríma","Rohirrim",itsGood = false,R.mipmap.grima,"Aunque en sus comienzos fue un siervo leal al Rey de Rohan, el mago Saruman le influenció de tal manera que Gríma cayó bajo el dominio del mal. De esta forma se erigió en el oscuro espía del mago de Isengard y se encargó de debilitar a Théoden con su lengua bífida, utilizando palabras astutas hasta que el rey casi no podía incorporarse del trono.")
        val gorbag = Personaje("Gorbag","Orco",itsGood = false,R.mipmap.gorbag,"Gorbag era un capitán orco de Cirith Ungol, originariamente de Minas Morgul. Se disputó con Shagrat la cota de mithril de Frodo luego de capturarlo. Esta disputa ocasionó una pelea entre los orcos dirigidos por Gorbag y los dirigidos por Shagrat. Tras la pelea, muertos casi todos los orcos de ambos bandos, Gorbag intenta atacar a Shagrat por la espalda, pero éste se da cuenta y lo mata.")
        val barbol = Personaje("Bárbol","Ent",itsGood = true,R.mipmap.barbol,"Más antiguo de lo que se puede recordar, el Ent Bárbol es uno de los últimos supervivientes de su especie, los ya olvidados pastores de árboles del Bosque de Fangorn que una vez vivieron en todos los bosques de la Tierra-media. Sabíos pero lentos a la hora de actuar, los Ents son convencidos por Bárbol, tras conocer a Merry y Pippin, para que se levanten y utilicen su antigua fuerza para luchar contra la oscuridad que amenaza su mundo. Bárbol dirigirá la Marcha de los Ents que acabará con la inundación y destrucción de Isengard.")
        val galadriel = Personaje("Galadriel","Elfa",itsGood = true,R.mipmap.galadriel,"Perteneciente al linaje de los Noldor, es hija de Finarfin y Eärwen. Llegó a la Tierra Media durante el exilio de los Noldor y allí vivió un tiempo en el reino de Doriath, donde conoció al que sería su esposo, Celeborn. Durante la Segunda Edad del Sol le fue entregado uno de los tres anillos élficos, Nenya, y a partir de la Tercera Edad del Sol se hizo cargo del gobierno del bosque de Lothlórien junto a su esposo.")
        val bilbo = Personaje("Bilbo","Hobbit",itsGood = true,R.mipmap.bilbo,"Hijo de Bungo Bolsón y Belladonna Tuk, es el protagonista de la novela El hobbit. En el año 2941 de la Tercera Edad del Sol, Bilbo fue convencido por Gandalf y un grupo de enanos para embarcarse en una aventura con el objetivo de recuperar el tesoro de Erebor y en la que acabó encontrando el Anillo Único, hasta entonces en manos de la criatura Gollum. Tras la muerte de su primo segundo Drogo y de su esposa Prímula, Bilbo adoptó al hijo de ambos, Frodo, al que acabó convirtiendo en su heredero.")
        val elrond = Personaje("Elrond","Peredhil",itsGood = true,R.mipmap.elrond,"Señor y fundador de Rivendel, hijo de Eärendil y Elwing y hermano gemelo de Elros, de quien descendieron los reyes de Númenor, Gondor y Arnor. Como peredhil, eligió pertenecer a la raza de los elfos y así se convirtió en el heraldo del rey Gil-Galad de los Noldor. De él recibió el anillo Vilya, con el cual protegió Rivendel de los ojos del enemigo.")
        val eomer = Personaje("Éomer","Hombre",itsGood = true,R.mipmap.eomer,"Tercer Mariscal de la Marca, sobrino del rey Théoden de Rohan y hermano mayor de Éowyn. Fue adoptado por su tío debido a la muerte de sus padres y, tiempo después, tras morir su primo Théodred, se convirtió en el heredero al trono.")
        val eowyn = Personaje("Éowyn","Mujer",itsGood = true,R.mipmap.eowyn,"Sobrina del rey Théoden de Rohan y hermana menor de Éomer. Tras la muerte de sus padres, fue adoptada por su tío y vivió con él en el castillo de Meduseld. Allí, y debido a su hermosura, despertó la curiosidad de Gríma Lengua de Serpiente, consejero de Théoden, que la deseaba en secreto.")
        val faramir = Personaje("Faramir","Dúnedai",itsGood = true,R.mipmap.faramir,"Capitán de los montaraces de Ithilien, segundo hijo de Denethor II y Finduilas y, por tanto, hermano menor de Boromir. Su padre siempre prefirió a Boromir y solía despreciar a Faramir, pero esto no impidió que los hermanos estuvieran muy unidos.")
        val theoden = Personaje("Théoden","Hombre",itsGood = true,R.mipmap.theoden,"Rey de Rohan, hijo de Thengel y Morwen. Tiempo después de asumir el trono, su consejero Gríma, que a la vez era servidor de Saruman, fue debilitando su mente con sus bisbiseos y consejos.")
        val mauhur = Personaje("Mauhúr","Uruk-hai",itsGood = false,R.mipmap.mauhur,"Mauhúr fue un Uruk-hai, capitán además, al servicio de Saruman durante la Guerra del Anillo. Fue enviado por este en ayuda de la tropa uruk que llevaba a cautivos Merry y a Pippin, liderada por Uglúk. Se reunió con estos poco antes de que llegaran a Fangorn, lugar donde un día después perdería la vida a manos del recién exiliado Éomer y sus Rohirrim.")
        val berserker = Personaje("Berserker","Uruk-hai",itsGood = false,R.mipmap.berserker,"Es un tipo de Uruk-hai, más grande y fuerte, dotado de una resistencia excepcional. Son seres irracionales, extremadamente violentos y que no temen a la muerte. Su estilo de lucha es agresivo y, tal y como se puede ver en Las Dos Torres, llevaban el cuerpo desnudo salvo por un casco, el cual no dejaba ver sus ojos, unos guanteletes y una especie de calzón. Únicamente son usados por Saruman en la Batalla de Cuernavilla como rompefilas; subidos a las escaleras de asedio cuando estas eran puestas en el muro, su único objetivo era distraer a los elfos y despejar el camino al grueso del ejército uruk. La mayoría de ellos no tardaron en morir, sin embargo, se llevaron a un buen número de elfos con ellos.")
        val radagast = Personaje("Radagast","Maiar",itsGood = true,R.mipmap.radagast,"Apodado 'El Pardo', Radagast tenía una especial afinidad con los animales salvajes de la Tierra Media, y era más sabio que todos los hombres en todo lo relacionado con las hierbas y las bestias. Se decía que conocía todas las lenguas de los pájaros, y era tenido por un 'maestro de formas y tonalidades'.")
        val balrog = Personaje("Balrog","Maiar(corrupto)",itsGood = false,R.mipmap.balrog,"Los balrogs son Maiar al servicio de Melkor descritos como enormes y amenazantes humanoides, con la habilidad de controlar el fuego, la oscuridad y las sombras. Inducían terror en enemigos y aliados por igual, y la sola mención de su nombre hacía temer a los más valerosos guerreros. Solían estar armados con látigos ígneos de varias puntas, y a veces con enormes espadas de fuego. Se deja entrever en los libros de Tolkien que los balrogs eran terriblemente poderosos, ya que requerían un esfuerzo colosal para ser destruidos; solo los dragones podían rivalizar con ellos en ferocidad y destrucción.")

        return mutableListOf(berserker,radagast,balrog,mauhur,theoden,faramir,eomer,eowyn,bilbo,boromir,elrond,reyBrujo,legolas,barbol,frodo,saruman,gimli,gandalf,grima,aragorn,gollum,meriadoc,sam,arwen,sauron,galadriel,peregrin,gorbag).apply { shuffle() }
    }
}